#!/usr/bin/env python3

import csv
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('csv')
parser.add_argument('mp3')
parser.add_argument('-t', '--title', required=True)
parser.add_argument('-p', '--performer', required=True)
parser.add_argument('--date')
parser.add_argument('--genre')
parser.add_argument('--encoding', default='utf-8-sig')
args = parser.parse_args()

with open(args.csv, encoding=args.encoding) as f:
    reader = csv.DictReader(f, delimiter='\t')

    if args.date:
        print(f'REM DATE {args.date}')

    if args.genre:
        print(f'REM GENRE {args.genre}')

    print(f'TITLE "{args.title}"')
    print(f'PERFORMER "{args.performer}"')
    print(f'FILE "{args.mp3}" MP3')

    for idx, row in enumerate(reader):
        performer, title = row['Name'].split(' - ')
        start = row['Start']
        track_no = idx + 1

        print(f'  TRACK {track_no:02} AUDIO')
        print(f'    PERFORMER "{performer}"')
        print(f'    TITLE "{title}"')
        print(f'    INDEX 01 {start}')
